name: Ansible roles testing with molecule

on:
  # push:
  #   branches: [ "master" ]
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: 'playbooks/roles'

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2404
        #   - debian13
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      - name: Disable AppArmor on Debian.
        run: |
            set -x
            sudo apt update
            sudo apt-get install apparmor-profiles
            sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        if: ${{ startsWith(matrix.distro, 'debian') }}

      - name: Run Molecule tests for apache role.
        working-directory: playbooks/roles/apache
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
    
      - name: Run Molecule tests for app role.
        working-directory: playbooks/roles/app
        run: molecule converge && molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule tests for database role.
        working-directory: playbooks/roles/database
        run: molecule converge && molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule tests for monitoring role.
        working-directory: playbooks/roles/monitoring
        run: molecule converge && molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule tests for node_exporter role.
        working-directory: playbooks/roles/node_exporter
        run: molecule converge && molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}